### ISSUE TITLE
Dendro dating overview chart is wrong

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_browser_client#291]

**Comment by johanvonboer** [comment]
This has been removed temporarily, but should be fixed and re-added.

**Comment by visead** [comment]
Still not correct, or broken again, example from [site 4169](https://browser.sead.se/site/4169)

![Image](https://github.com/user-attachments/assets/5618ff5e-2f4f-4a27-b0e2-dc1172eeae18)
